from pydantic import BaseModel, Field
from typing import Literal, Optional


class SceneStyle(BaseModel):
    """Style configuration for scene captions"""

    font_size: int = Field(default=48, description="Font size for captions")
    font_color: str = Field(default="#FFFFFF", description="Font color (hex)")
    background_color: str = Field(
        default="#000000AA", description="Background color with alpha"
    )
    position: Literal["top", "center", "bottom"] = Field(default="bottom")


class Caption(BaseModel):
    """Caption/subtitle with timing"""

    text: str = Field(description="Caption text")
    start_time: float = Field(description="Start time in seconds")
    end_time: float = Field(description="End time in seconds")
    style: Optional[SceneStyle] = None


class Scene(BaseModel):
    """Scene definition for video"""

    id: str = Field(description="Unique scene identifier")
    duration: float = Field(description="Duration in seconds")
    type: Literal["image", "video", "text"] = Field(description="Scene type")
    content: str = Field(description="URL to asset or text content")
    transition: Literal["fade", "slide", "zoom", "none"] = Field(default="fade")
    transition_duration: float = Field(
        default=0.5, description="Transition duration in seconds"
    )


class AudioTrack(BaseModel):
    """Audio track for video"""

    type: Literal["music", "voiceover", "sfx"] = Field(description="Audio type")
    url: str = Field(description="URL to audio file in S3")
    start_time: float = Field(default=0.0, description="Start time in seconds")
    volume: float = Field(default=0.7, ge=0.0, le=1.0, description="Volume level")
    fade_in: float = Field(default=0.0, description="Fade in duration in seconds")
    fade_out: float = Field(default=0.0, description="Fade out duration in seconds")


class VideoMetadata(BaseModel):
    """Video metadata"""

    target_platforms: list[Literal["tiktok", "instagram", "youtube"]] = Field(
        default=["tiktok", "instagram", "youtube"]
    )
    hashtags: Optional[list[str]] = None
    created_at: str = Field(description="ISO 8601 timestamp")


class VideoScript(BaseModel):
    """Complete video script generated by AI"""

    id: str = Field(description="Unique script identifier")
    topic: str = Field(description="Video topic")
    title: str = Field(description="Video title")
    description: str = Field(description="Video description")
    total_duration: float = Field(description="Total duration in seconds")
    scenes: list[Scene] = Field(description="List of scenes")
    captions: list[Caption] = Field(description="List of captions")
    audio_tracks: list[AudioTrack] = Field(description="List of audio tracks")
    metadata: VideoMetadata = Field(description="Video metadata")


class GeminiRequest(BaseModel):
    """Request to generate video script"""

    topic: str = Field(description="Topic for video generation")
    target_duration: float = Field(default=60, description="Target duration in seconds")
    target_platforms: list[Literal["tiktok", "instagram", "youtube"]] = Field(
        default=["tiktok", "instagram", "youtube"]
    )
    style: Literal["educational", "entertaining", "informative", "promotional"] = Field(
        default="entertaining"
    )


class GeminiResponse(BaseModel):
    """Response from script generation"""

    success: bool
    script: Optional[VideoScript] = None
    error: Optional[str] = None
