/**
 * Shared TypeScript types for Auto-Short-Factory
 */

/**
 * Workflow state machine states
 */
export enum WorkflowState {
    IDLE = 'IDLE',
    DOWNLOADING_INPUT = 'DOWNLOADING_INPUT',
    GENERATING_SCRIPT = 'GENERATING_SCRIPT',
    DOWNLOADING_ASSETS = 'DOWNLOADING_ASSETS',
    ASSEMBLING_VIDEO = 'ASSEMBLING_VIDEO',
    UPLOADING_OUTPUT = 'UPLOADING_OUTPUT',
    COMPLETED = 'COMPLETED',
    FAILED = 'FAILED',
}

/**
 * Scene definition for video script
 */
export interface Scene {
    id: string;
    duration: number; // in seconds
    type: 'image' | 'video' | 'text';
    content: string; // URL to asset or text content
    transition?: 'fade' | 'slide' | 'zoom' | 'none';
    transitionDuration?: number; // in seconds
}

/**
 * Caption/subtitle timing
 */
export interface Caption {
    text: string;
    startTime: number; // in seconds
    endTime: number; // in seconds
    style?: {
        fontSize?: number;
        fontColor?: string;
        backgroundColor?: string;
        position?: 'top' | 'center' | 'bottom';
    };
}

/**
 * Audio instruction for video
 */
export interface AudioTrack {
    type: 'music' | 'voiceover' | 'sfx';
    url: string; // URL to audio file in S3
    startTime?: number; // in seconds
    volume?: number; // 0.0 to 1.0
    fadeIn?: number; // in seconds
    fadeOut?: number; // in seconds
}

/**
 * Complete video script generated by AI
 */
export interface VideoScript {
    id: string;
    topic: string;
    title: string;
    description: string;
    totalDuration: number; // in seconds
    scenes: Scene[];
    captions: Caption[];
    audioTracks: AudioTrack[];
    metadata: {
        targetPlatforms: ('tiktok' | 'instagram' | 'youtube')[];
        hashtags?: string[];
        createdAt: string;
    };
}

/**
 * S3 asset metadata
 */
export interface S3Asset {
    bucket: string;
    key: string;
    url: string;
    type: 'image' | 'video' | 'audio';
    size?: number; // in bytes
    uploadedAt?: string;
}

/**
 * Video metadata and output information
 */
export interface VideoMetadata {
    id: string;
    scriptId: string;
    topic: string;
    title: string;
    duration: number; // in seconds
    width: number;
    height: number;
    fps: number;
    fileSize: number; // in bytes
    codec: string;
    outputUrl: string; // S3 URL
    thumbnailUrl?: string; // S3 URL
    createdAt: string;
    processingTime?: number; // in seconds
}

/**
 * Workflow job configuration
 */
export interface WorkflowJob {
    id: string;
    state: WorkflowState;
    topic?: string;
    scriptId?: string;
    videoId?: string;
    createdAt: string;
    updatedAt: string;
    error?: {
        message: string;
        stack?: string;
        timestamp: string;
    };
}

/**
 * Gemini API request/response types
 */
export interface GeminiRequest {
    topic: string;
    targetDuration?: number; // in seconds
    targetPlatforms?: ('tiktok' | 'instagram' | 'youtube')[];
    style?: 'educational' | 'entertaining' | 'informative' | 'promotional';
}

export interface GeminiResponse {
    success: boolean;
    script?: VideoScript;
    error?: string;
}

/**
 * Video generation request/response types
 */
export interface VideoGenerationRequest {
    script: VideoScript;
    outputBucket: string;
    outputKey: string;
}

export interface VideoGenerationResponse {
    success: boolean;
    metadata?: VideoMetadata;
    error?: string;
}

/**
 * Error types
 */
export class WorkflowError extends Error {
    constructor(
        message: string,
        public readonly state: WorkflowState,
        public readonly originalError?: Error
    ) {
        super(message);
        this.name = 'WorkflowError';
    }
}

export class S3Error extends Error {
    constructor(
        message: string,
        public readonly bucket: string,
        public readonly key: string,
        public readonly originalError?: Error
    ) {
        super(message);
        this.name = 'S3Error';
    }
}

export class VideoProcessingError extends Error {
    constructor(
        message: string,
        public readonly scriptId: string,
        public readonly originalError?: Error
    ) {
        super(message);
        this.name = 'VideoProcessingError';
    }
}
